- hosts: all
  sudo: True
  vars_files:
  - "~/Projects/conf/azure-sentry.yml"
  roles:
    - common
    - python
    - supervisor
    - role: nginx
      nginx_sites: none
    - postgres
    - sentry
